###########################
#    Run Configuration    #
###########################

grid_world:
  # GridWorld settings:
  # - number of rows and columns
  # - max active resources on grid
  # - max tier of the tier type resources
  grid_rows: &grid_rows 5
  grid_cols: &grid_cols 5
  max_active_resources: 3
  max_tier: 1

observation_handler:
  # Observation handler settings:
  # - grid_rows / grid_cols: fix the maximum observation space size
  # - max_steps: number of steps in an episode until truncated
  grid_rows: *grid_rows
  grid_cols: *grid_cols
  max_steps: 100

renderer:
  # Renderer settings:
  # - grid_rows / grid_cols: used to calculate display size and layout
  grid_rows: *grid_rows
  grid_cols: *grid_cols

agent:
  # Agent settings:
  # - grid_rows / grid_cols: defines the grid the agent can move in
  # - starting_score: initial score of the agent
  grid_rows: *grid_rows
  grid_cols: *grid_cols
  starting_score: 40
